---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.8-wheezy

inputs:
  - name: repo

outputs:
  - name: bin

run:
  path: bash
  args: 
    - -c
    - |
      cd repo
      go build
      cd ..
      mv repo/repo bin/my-executable
